CREATE DATABASE SA_ESCOLA;

USE SA_ESCOLA;

CREATE TABLE  TB_CAMPUS(
  CD_CAMPUS INT PRIMARY KEY,
  CIDADE VARCHAR(45),
  ENDERECO VARCHAR (45)
);

CREATE TABLE TB_CURSO(
   CD_CURSO INT PRIMARY KEY,
   NOME_CURSO VARCHAR(45),
   TURNO VARCHAR(45),
   DURACAO DATE,
   VALOR DOUBLE,
   CD_CAMPUS INT,
   FOREIGN KEY (CD_CAMPUS) REFERENCES TB_CAMPUS(CD_CAMPUS)
);

CREATE TABLE TB_ALUNO(
  REGITRO_ACADEMICO INT PRIMARY KEY,
  NOME VARCHAR(45),
  DT_NASC DATE,
  CPF VARCHAR(11),
  SEXO ENUM('M','F','OUTRO')	
 );
 
 CREATE TABLE TB_MATRICULA(
   CD_MATRICULA INT PRIMARY KEY,
   DT_MATRICULA DATE,
   REGITRO_ACADEMICO INT,
   CD_CURSO INT,
   FOREIGN KEY (REGITRO_ACADEMICO) REFERENCES TB_ALUNO(REGITRO_ACADEMICO),
   FOREIGN KEY (CD_CURSO) REFERENCES TB_CURSO(CD_CURSO)
 );
 
 -- LISTA DE BUSCAS
 
 -- 1 
SELECT A.NOME_CURSO, B.CIDADE
FROM TB_CURSO A 
INNER JOIN TB_CAMPUS B ON A.CD_CAMPUS = B.CD_CAMPUS
WHERE B.CIDADE = 'VITORIA';

-- 2
SELECT A.NOME_CURSO, B.CIDADE
FROM TB_CURSO A 
INNER JOIN TB_CAMPUS B ON A.CD_CAMPUS = B.CD_CAMPUS
ORDER BY A.NOME_CURSO ASC;

-- 3 
SELECT A.NOME_CURSO, A.VALOR
FROM TB_CURSO A 
INNER JOIN TB_CAMPUS B ON A.CD_CAMPUS = B.CD_CAMPUS
ORDER BY A.VALOR DESC
LIMIT 5;

-- 4
SELECT A.NOME_CURSO, A.VALOR, B.CIDADE
FROM TB_CURSO A
INNER JOIN TB_CAMPUS B ON A.CD_CAMPUS = B.CD_CAMPUS
WHERE B.CIDADE = 'Serra'
ORDER BY A.VALOR ASC
LIMIT 1;

-- 5
SELECT TURNO, COUNT(*) AS NUM_CURSOS
FROM TB_CURSO
GROUP BY TURNO
ORDER BY NUM_CURSOS DESC
LIMIT 1;

-- 6
SELECT COUNT(*) AS NUM_CURSOS
FROM TB_CURSO
WHERE DATEDIFF(DURACAO, CURRENT_DATE) > (2.5 * 365);

-- 7
SELECT 





 
 
 
 
