CREATE DATABASE SA_ESCOLA;

USE SA_ESCOLA;

CREATE TABLE  TB_CAMPUS(
  CD_CAMPUS INT PRIMARY KEY,
  CIDADE VARCHAR(45),
  ENDERECO VARCHAR (45)
);

CREATE TABLE TB_CURSO(
   CD_CURSO INT PRIMARY KEY,
   NOME_CURSO VARCHAR(45),
   TURNO VARCHAR(45),
   DURACAO DATE,
   VALOR DOUBLE,
   CD_CAMPUS INT,
   FOREIGN KEY (CD_CAMPUS) REFERENCES TB_CAMPUS(CD_CAMPUS)
);

CREATE TABLE TB_ALUNO(
  REGITRO_ACADEMICO INT PRIMARY KEY,
  NOME VARCHAR(45),
  DT_NASC DATE,
  CPF VARCHAR(11),
  SEXO ENUM('M','F','OUTRO')	
 );
 
 CREATE TABLE TB_MATRICULA(
   CD_MATRICULA INT PRIMARY KEY,
   DT_MATRICULA DATE,
   REGITRO_ACADEMICO INT,
   CD_CURSO INT,
   FOREIGN KEY (REGITRO_ACADEMICO) REFERENCES TB_ALUNO(REGITRO_ACADEMICO),
   FOREIGN KEY (CD_CURSO) REFERENCES TB_CURSO(CD_CURSO)
 );
 
 -- LISTA DE BUSCAS
 
 -- 1 
SELECT CIDADE FROM TB_CAMPUS
 
 
 
 
